wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1680509496.167028
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.9.12
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 64
buffer_size:
  desc: null
  value: 10
conf_host:
  desc: null
  value: DSFHSWF-PowerEdge-R7525
conf_jobnum:
  desc: null
  value: c700d7f9-50ce-4adc-8352-eeac65ff5d7b
conf_timestamp:
  desc: null
  value: '2023-04-03 10:11:34.859659'
dataset:
  desc: null
  value: seq-mnist
debug_mode:
  desc: null
  value: 0
disable_log:
  desc: null
  value: 0
distributed:
  desc: null
  value: 'no'
ignore_other_metrics:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.0001
minibatch_size:
  desc: null
  value: 64
model:
  desc: null
  value: er
n_epochs:
  desc: null
  value: 10
non_verbose:
  desc: null
  value: 0
notes:
  desc: null
  value: null
nowand:
  desc: null
  value: 0
optim_mom:
  desc: null
  value: 0.0
optim_nesterov:
  desc: null
  value: 0
optim_wd:
  desc: null
  value: 0.0
seed:
  desc: null
  value: null
validation:
  desc: null
  value: 0
wandb_entity:
  desc: null
  value: regaz
wandb_project:
  desc: null
  value: mammoth
