wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1681715433.115163
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.12
      5: 0.14.0
      8:
      - 5
batch_size:
  desc: null
  value: 32
buffer_size:
  desc: null
  value: 500
conf_host:
  desc: null
  value: DSFHSWF-PowerEdge-R7525
conf_jobnum:
  desc: null
  value: 43f56c14-252e-4270-9794-9a8075d11567
conf_timestamp:
  desc: null
  value: '2023-04-17 09:10:31.723664'
dataset:
  desc: null
  value: seq-cifar10
debug_mode:
  desc: null
  value: 0
disable_log:
  desc: null
  value: 0
distributed:
  desc: null
  value: 'no'
ignore_other_metrics:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.0001
minibatch_size:
  desc: null
  value: 32
model:
  desc: null
  value: er
n_epochs:
  desc: null
  value: 20
non_verbose:
  desc: null
  value: 0
notes:
  desc: null
  value: null
nowand:
  desc: null
  value: 0
optim_mom:
  desc: null
  value: 0.0
optim_nesterov:
  desc: null
  value: 0
optim_wd:
  desc: null
  value: 0.0
seed:
  desc: null
  value: null
validation:
  desc: null
  value: 0
wandb_entity:
  desc: null
  value: fneubuerger
wandb_project:
  desc: null
  value: mammoth
