# TEP Validation - tepcfc and teplstm backbones

python_cmd: python
venv_path: ../.venv/bin/activate
base_path: ./mammoth

gpus:
  - 0
  - 1

global_args:
  n_epochs: 1
  batch_size: 32
  num_workers: 0

datasets:
  - tennessee-eastman

models:
  - er

backbones:
  - tepcfc
  - teplstm

seeds:
  - 0

model_args:
  er:
    buffer_size: 200

dataset_args:
  tennessee-eastman:
    lr: 0.001
